# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=14)),
                ('year_issued', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('owned', models.BooleanField(default=False)),
            ],
        ),
    ]
